version: 1
jobs:
  build:
    workingDirectory: ../backend
    docker:
      - image:
          circle/alpine: 12.12.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: `yarn`
      - run:
          name: Run tests
          command: `yarn test`
workflows:
  version: 1
  build-and-deploy:
    jobs:
      - build

